export default [
  { id: "AP", n: "Andhra Pradesh" },
  { id: "AR", n: "Arunachal Pradesh" },
  { id: "AS", n: "Assam" },
  { id: "BR", n: "Bihar" },
  { id: "CT", n: "Chhattisgarh" },
  { id: "DL", n: "Delhi" },
  { id: "GA", n: "Goa" },
  { id: "GJ", n: "Gujarat" },
  { id: "HR", n: "Haryana" },
  { id: "HP", n: "Himachal Pradesh" },
  { id: "JK", n: "Jammu and Kashmir" },
  { id: "JH", n: "Jharkhand" },
  { id: "KA", n: "Karnataka" },
  { id: "KL", n: "Kerala" },
  { id: "MP", n: "Madhya Pradesh" },
  { id: "MH", n: "Maharashtra" },
  { id: "MN", n: "Manipur" },
  { id: "ML", n: "Meghalaya" },
  { id: "MZ", n: "Mizoram" },
  { id: "NL", n: "Nagaland" },
  { id: "OR", n: "Orissa" },
  { id: "PB", n: "Punjab" },
  { id: "RJ", n: "Rajasthan" },
  { id: "SK", n: "Sikkim" },
  { id: "TN", n: "Tamil Nadu" },
  { id: "TR", n: "Tripura" },
  { id: "UP", n: "Uttar Pradesh" },
  { id: "UT", n: "Uttarakhand" },
  { id: "WB", n: "West Bengal" },
];